### ISSUE TITLE
New Release/Tag

### ISSUE THREAD

**Issue by lastlink** [msaccess-vcs-integration/msaccess-vcs-integration#77]
I've noticed it's been like several years since a downloadable release has been made. Could you @timabell push a new release?

Typically to push a release you use tags.
E.g.
`git tag "v1.0.1" -a "2018 release \n template support, ui_ribbon w/ buttons \n etc"`
`git push origin --tags`

Also @timabell is there a chance you could add me on as a direct contributor to this project so that I may more directly work on the issues & pull requests?

I'm also thinking about writing some unit tests using [rubberduckvba](http://rubberduckvba.com/). They have some code analysis that gives a bunch of naming recommendations & explicitly variable declarations that should be implemented.

**Comment by timabell** [comment]
@lastlink added to contributors :+1:

**Comment by lastlink** [comment]
Ok, after my pull request has been approved I'll go ahead & add the release.

**Comment by hansfn** [comment]
Any chance of getting a stable release? Version [v1.0.1_beta](https://github.com/msaccess-vcs-integration/msaccess-vcs-integration/releases/tag/1.0.1_beta) was back in 2018 and is hidden by default since it's a beta release. It looks like the project hasn't had a release since 2015. You need to check the commit history to understand that the project isn't dead ;-)

**Comment by timabell** [comment]
> Any chance of getting a stable release? Version [v1.0.1_beta](https://github.com/msaccess-vcs-integration/msaccess-vcs-integration/releases/tag/1.0.1_beta) was back in 2018 and is hidden by default since it's a beta release. It looks like the project hasn't had a release since 2015. You need to check the commit history to understand that the project isn't dead ;-)

I'm doing much with this so couldn't say what's a good point for tagging so I'll leave it to any active maintainers to decide if/what to tag. I'm going to close this ticket just because the original ask was dealt with. I wouldn't personnally object if you opened a new one.
